### ISSUE TITLE
Spike: find what causes response time increase on Find MOJ data app when users > 20

### ISSUE THREAD

**Issue by hjribeiro-moj** [ministryofjustice/data-catalogue#143]
After performing tests with locust with different numbers of users, it was visible that response time time increases drastically with number of users.

Performance bottleneck seems to come from the django app as datahub performs normally when app is under load.

we need to investigate what could be causing this issue. 

Typically falls under "profiling" - potential starting point here: [Profiling Django](https://code.djangoproject.com/wiki/ProfilingDjango)

Potential areas of interest:

- gunicorn
- django 
- nginx
- others?

![Image](https://github.com/ministryofjustice/data-catalogue/assets/166705689/6182d0ea-4572-41b7-90aa-ee02ac260c21)

**Comment by mitchdawson1982** [comment]
Useful article - [](https://medium.com/building-the-system/gunicorn-3-means-of-concurrency-efbb547674b7)

**Comment by LavMatt** [comment]
gunicorn config https://stackoverflow.com/questions/38425620/gunicorn-workers-and-threads

**Comment by hjribeiro-moj** [comment]
attempt 1 

test 30 users, ramp up 10

workers=3



![Image](https://github.com/ministryofjustice/data-catalogue/assets/166705689/57df56f5-522b-41b9-b120-3f4f9dc0cc1a)

**Comment by hjribeiro-moj** [comment]
same as above, test 200 users:



![Image](https://github.com/ministryofjustice/data-catalogue/assets/166705689/2143d400-d023-4e42-9118-c2754dd110a4)

**Comment by hjribeiro-moj** [comment]
3 workers, 1 thread (100 users test)

**Comment by hjribeiro-moj** [comment]
3 workers, 2 threads (100 user test)



![Image](https://github.com/ministryofjustice/data-catalogue/assets/166705689/b8ca7a3b-e00f-4b2e-b632-7c62ed797c07)

**Comment by hjribeiro-moj** [comment]
gevent (pseudo threads worker) 3 workers 

30 users test



![Image](https://github.com/ministryofjustice/data-catalogue/assets/166705689/0a57893e-8193-4898-9552-58a48d59ab6f)

**Comment by hjribeiro-moj** [comment]
**summary**

|          | 3 workers gevent | 5 workers  | 3 workers |
|----------|------------------|------------|-----------|
| average  | 5.9 s            | 4.7s       | 6.1 s     |
| 95 %tile | 3.4s - 67s       | 4.6s - 17s | 6.1s - 9s |

**Comment by YvanMOJdigital** [comment]
write followup tickets for sprint 14 before close
