### ISSUE TITLE
Migrate GH repo for catalogue library

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/data-catalogue#17]
### Problem
Analytical Platform (AP) are re-purposing the [data-platform monorepo](https://github.com/ministryofjustice/data-platform) and re-naming to analytical-platform. We need to migrate our data-catalogue-specific components from this repo into our preferred structure of one repo for the Find MOJ Data App.

One of the existing components to migrate out is the `data-platform-catalogue` python library.

### Requirements
- [x] Move the catalogue library from AP's repo (data-platform) into `find-moj-data` repo .
- [x] Update the docs to remove references to data platform.

**Note:** We'll likely need some help from AP team with access to Pypi

## Acceptance criteria
- [x] Repo is defined in terraform in [data-platform's github management repo](https://github.com/ministryofjustice/data-platform-github-access)
- [x] library code moved across to `find-moj-data`
    - [ ] ~~[PREFERRED] new repo contains all history of library content from data-platform repo~~
- [ ] Releasing still deploys to Pypi

**Comment by MatMoore** [comment]
Related: https://github.com/ministryofjustice/data-platform/issues/4004

**Comment by tom-webber** [comment]
[repo definition](ministryofjustice/data-platform-github-access#27)

**Comment by MatMoore** [comment]
Merge everything in progress before picking this up

**Comment by MatMoore** [comment]
Ready to review here https://github.com/ministryofjustice/find-moj-data/pull/301

Split out https://github.com/ministryofjustice/find-moj-data/issues/302
