### ISSUE TITLE
Optimise ingestion

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/data-catalogue#179]
Ingestion of CaDeT data currently takes 3 hours. How do we optimise this either through code refactoring or through infrastructure resources so that it runs more quickly?

Mat M has done some early thinking around this https://mojdt.slack.com/archives/C06UQ5HSR25/p1720023149194019

**Comment by mitchdawson1982** [comment]
Matt and I paired on this on Friday and attempted another ingestion however this appeared to break Dev.

**Comment by mitchdawson1982** [comment]
Placing this back into Todo while I am looking at changing the workflows.

**Comment by mitchdawson1982** [comment]
Matt Laverty - [branch](https://github.com/ministryofjustice/data-catalogue/compare/main...optimise-domain-assignment)
These changes have significantly shortened the ingestion time. We identified that every domain was being matched against every regex pattern so approx 9k domains * 9k regex patterns.

Mitch Logging [branch](https://github.com/ministryofjustice/data-catalogue/tree/transformer-logging-tests)
Tom's WIP [branch](https://github.com/ministryofjustice/data-catalogue/compare/main...feat/fmd-201-add-ingestion-timing)
