### ISSUE TITLE
Check users are read-only in DataHub

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/data-catalogue#194]
When a user clicks a lineage link in the front end, they are taken to DataHub. At this point, what permissions do they have in the back end catalogue?

They should be read only and not have the ability to eg add, delete, etc.

**Comment by MatMoore** [comment]
I logged in to prod for the first time and my user appears to be read only:

- I am not assigned to any groups
- I can view everything, including analytics, glossary, and domains
- I cannot edit or remove metadata
  - If I try and add documentation I get an error saying I am Unauthorized
  - Same for adding owners, tags
  - Same for removing tags
- I can create private views but not public ones
