### ISSUE TITLE
Remove old Confluence docs

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/data-catalogue#20]
Should we archive some of the team stuff on https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4238802982/Data+Catalogue now we have the runbook?

Almost all of the pages relate to DaaP rather than the data catalogue and this page could go in the runbook https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4678549665/DataHub+catalogue
[Data Catalogue](https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4238802982/Data+Catalogue?atlOrigin=eyJpIjoiNWNlNjc0MjY3MGQ0NDBmNmEyMTQyZWRjYjQ1MzBlYTAiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ) in [Data Platform](https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform?atlOrigin=eyJpIjoiOTU5M2Q1YTJmODAxNGJlYWE5MDBlNDM2MmY2Y2U2NWYiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ)

**Comment by MatMoore** [comment]
I've moved everything to do with Data as a Product to the archive folder.

https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4745560150/DataHub+Deployment could be merged into the runbook

These ones could go in the runbook or stay here: 
- https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4310467410/Best+practices+for+development+deployment
- https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4536926298/Labs+Team+Ceremonies

I've left this one alone for now https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4490199291/Data+Platform+Glossary
