### ISSUE TITLE
Add logging to ingestion so we know how long each process takes

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/data-catalogue#206]
For each sub-process in CaDeT ingestion, log start, end and duration for that process

Make sure this covers all our custom code

- The 2 custom transformers https://github.com/ministryofjustice/data-catalogue/tree/main/ingestion/transformers
- display_in_catalogue tagger
- cadet database source
- justice data source

Ideally we should also have timings for the built in sources - is this possible to do? If not we can subtract the timings of the custom code from the total runtime.

**Comment by tom-webber** [comment]
The ingestion workflows are currently failing, [likely due to a mismatch between the latest release of the datahub CLI and the latest release of datahub gms](https://datahubspace.slack.com/archives/CUMUWQU66/p1721908299380149).

**Comment by tom-webber** [comment]
For handover - need to add the timing function to the changes merged into main since the ticket was opened (branch needs rebasing, then add the timing function to new parts of the ingestion code).
