### ISSUE TITLE
🦺  Make sure code for fetching details pages handles missing information gracefully

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/data-catalogue#21]
### Describe the bug.

We recently had a bug where `get_table_details` threw a KeyError that prevented the page from loading.

This is now fixed, but in general if expected metadata is missing, it would be better to continue to render the rest of the page (perhaps with a warning about the missing data)

To prevent this from happening again, we should ensure that our GraphQL response parsing code (mainly `graphql_helpers.py`) handles any missing data by returning some kind of empty value (e.g. None, empty list, empty dictionary).

When we parse nested values (e.g. `ownership.owners.owner`) we should make sure that we catch any `KeyError` on any of the intermediate keys, and return the empty value in that case.

When these errors happen, we should make sure we log them as errors so we can still debug the issue (see https://github.com/ministryofjustice/find-moj-data/issues/216)

In the frontend templates, we can use conditionals or the [default filter](https://docs.djangoproject.com/en/5.0/ref/templates/builtins/#default) to change what we display if data is missing.

**Comment by LavMatt** [comment]
Will be better doing this post refactor now that has started

And this will also look to address bug where methods return results even when a given urn does not exist

**Comment by LavMatt** [comment]
Actually this is now all likely to be covered within the wider refactor

**Comment by murdo-moj** [comment]
https://github.com/ministryofjustice/find-moj-data/issues/327 fixing this bug is the parent problem of this particular bug

**Comment by hjribeiro-moj** [comment]
After review we decided to close ticket as graphql_helper is defensive enough. Is any `KeyError` is raised and seen on alerts, we can fix those particular instances.
