### ISSUE TITLE
Assessment prep

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/data-catalogue#23]
Demo find-moj-data, Demo datahub frontend, Metadata and ingestion @MatMoore @LavMatt 
- no slides
- [x] video 

 Users and product: intro, user personas, beta plan and success @seanprivett 
- [ ] slides
- [ ] video
 
Open standards, common components and patterns,Design and content iterations from UR and accesibility tests on prototypes and figma @RNTjustice @alex-vonfeldmann @mitchdawson1982 
- [ ] slides
- [ ] video

Choose the right tools and technology - **slides no video** - @tom-webber 
- [x] [slides](https://docs.google.com/presentation/d/1gceWOAYirgbLcaw3zKRbg1r98BLuIZW-xgFbxZdslmA/edit#slide=id.g2c96cae725a_0_152)

Operate a reliable service - **slides no video** @tom-webber  @jemnery 
- [x] [slides](https://docs.google.com/presentation/d/1gceWOAYirgbLcaw3zKRbg1r98BLuIZW-xgFbxZdslmA/edit#slide=id.g2c96cae725a_0_231)

Security and Privacy **slides no video** @jemnery 
- [ ] slides

Team and stakeholders @YvanMOJdigital 
- [ ] slides
- [ ] video

**Comment by YvanMOJdigital** [comment]
Videos should be around 10 mins long max

**Comment by murdo-moj** [comment]
## The find-moj-data service (AKA the Data Catalogue)

### Setting the scene
* What is the history of our problem area in the business? Who is funding us?
* Who are our users?
* What is the problem we are aiming to solve?
* How does our solution improve on previous solutions eg the Data Discovery tool?
* What is the scoping for alpha? Why did we choose this?
* What metrics do we have for the success of the service?

### Service demonstration
* What does the find-moj-data service look like?
* What metadata has already been put into the catalogue? Is this reflective of how we want metadata to look ideally?

### Putting users first
* What are our user personas?
* How have we accounted for users with different accessibility needs?
* How have we iterated content to incorporate user needs based on user research?
* How have we iterated design to incorporate user needs?

### Technology matters
* How did we choose DataHub as our engine?
* How did we chose our hosting?
* What is our development approach?
* How are we considering our security posture?
* How are we considering service reliability?

### Team structure
* What is our team structure? What ceremonies do we have?
* How are we working with other connected stakeholders eg DIP?
* What skill areas are we strong in?
* Which areas are we weaker in? Are we working to address those gaps?

### Beta and beyond
* What is our roadmap for after alpha?
