### ISSUE TITLE
Upgrade DataHub to 14.0.2

### ISSUE THREAD

**Issue by tom-webber** [ministryofjustice/data-catalogue#250]
## Context

DataHub have released a new version with features we'll need for upcoming tickets (notably https://github.com/ministryofjustice/find-moj-data/issues/701). 

[Here's our runbook for upgrading our DataHub instance](https://runbooks.data-catalogue.service.justice.gov.uk/documentation/runbooks/005-upgrade-datahub.html#update-datahub-version)

A new DataHub helm chart has been released, so we can update our helm reference in the deploy workflows..

[Current helm tags we're releasing to compare against](https://github.com/ministryofjustice/data-catalogue/blob/1c78400532ec1389c95b5efd74ab595902f1ef22/.github/workflows/deploy-staged.yml#L18-L19)

This is an opportunity to test out the comms process for rolling out an upgrade. If there are any follow-up notes / improvements, please add them to the runbook.

**Breaking changes**

* There's a [breaking change in aspect creation](https://datahubproject.io/docs/how/updating-datahub/#0140), but I'm not sure if we do any aspect creation in our current ingestion flows.
* API `/v1` endpoints are noted for depreciation.

**Comment by LavMatt** [comment]
we can merge this and deploy on monday
