### ISSUE TITLE
Set up Cloud Platform Alerting for DataHub

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/data-catalogue#29]
Follows on from ministryofjustice/data-catalogue#28

Set up monitoring-based alerting for:

- DataHub application
- Kafka

[Cloud Platform guide to observability](https://user-guide.cloud-platform.service.justice.gov.uk/#observability)

#### PagerDuty

Consider (if time) adding PagerDuty as a middleware broker for what/where/when. Even if we're not actually implementing an on-call rota.

### Requirements
- [x] [Define and deploy custom alerts with PrometheusRule](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts)
  - [ ] high latency
  - [x] errors
  - [x] resource depletion
  - [ ] stalled data ingestion
  - [ ] security anomalies
- [x] Set up [pingdom](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-pingdom-checks.html#creating-pingdom-checks) to alert if either of our main services (or important endpoints) go down

**Comment by tom-webber** [comment]
Add PrometheusRule alerts for the DataHub namespaces in Cloud Platform, pointing at the aws resources (rds, opensearch), resource usage metrics (for the `datahub-gms` pod), deployment metrics, pod status metrics (out of memory, crashloop backoff, frequent restarts), ingress metrics (modsecurity blocking events, servicing error responses).

Opensearch metrics may not be suffificient, as during a recent bottleneck event, Opensearch was unresponsive but Prometheus metrics were absent during the period of downtime. 

CP have recently put together a [terraform opensearch cloudwatch alarm module](https://github.com/ministryofjustice/cloud-platform-terraform-opensearch-cloudwatch-alarm), but it is not yet suitable for use in user namespaces, as there’s no mechanism to instantiate infrastructure for exporting events to 
- Create an sns topic
- Deliver the events to SNS to be picked up by the reporting infrastructure

**Comment by tom-webber** [comment]
[CP issue for adding routes for alertmanager](https://github.com/ministryofjustice/cloud-platform/issues/5632)
