### ISSUE TITLE
Implement Thanos for long-term storage of Prometheus logs

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/data-catalogue#30]
Long term storage of Prometheus metrics
[For historical analysis and alerting on long-term trends, we can use Thanos](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/prometheus.html#thanos)

**Comment by MatMoore** [comment]
This is enabled by default so we don't need to do anything 🎉 

https://mojdt.slack.com/archives/C03QZ776JVA/p1716386918954279
