### ISSUE TITLE
DevSecOps for DataHub and find-moj-data

### ISSUE THREAD

**Issue by tom-webber** [ministryofjustice/data-catalogue#32]
We should be aware of any security vulnerabilities that have been raised for DataHub (see [the Security tab on the GitHub page](https://github.com/datahub-project/datahub/security))

We should especially be alerted when a vulnerability is raised that applies for any of our deployed DataHub versions

Scans to look into:
- software composition analysis (SCA)
- static application security testing (SAST)
- dynamic application security testing (DAST)

**Comment by MatMoore** [comment]
This looks like a useful integration https://github.com/kunalnagarco/action-cve

**Comment by tom-webber** [comment]
[Added action-cve to find-moj-data](https://github.com/ministryofjustice/find-moj-data/pull/361).

[Dependabot isn't capable of detecting helm chart version changes](https://github.com/dependabot/dependabot-core/issues/2237), so another solution will be needed (e.g. [renovate](https://github.com/renovatebot/renovate)) for monitoring changes with DataHub helm charts in the data-catalogue repo.

We will also want to subscribe to new [vulnerabilities reported on the DataHub repo](https://github.com/datahub-project/datahub/security)

**Comment by tom-webber** [comment]
Created a [workflow](https://github.com/ministryofjustice/data-catalogue/pull/128) to post security [DataHub advisories](https://github.com/datahub-project/datahub/security/advisories) posted on GitHub to the alerts Slack channel. 

Attempted to repackage deployment into a helm chart to allow use of a [workflow action to track helm chart versions as they are released, and automatically raise pull requests](https://github.com/hckops/actions?tab=readme-ov-file#helm-dependencies-action). This was unsuccessful due to limitations with dictating helm chart installation order.

Have settled for subscribing the alert slack channel to releases from the DataHub helm repository, and manual updates.
