### ISSUE TITLE
Spike: Datahub's Platforms and using custom defined Platforms

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/data-catalogue#349]
## Are we using Datahub's Platforms in the best way
We have introduced (or soon will introduce) some additional metadata properties into the catalogue, see issue https://github.com/ministryofjustice/find-moj-data/issues/1023

There does appear to be some overlap (or potential overlap) between:

- `Platform` - An area within Datahub where the data are loaded - currently for cadet data this is `dbt`
- `dc_where_to_access_data` - An old property we used near the start of the project which we still have populated (cadet set as `Analytical Platform`) but don't do anything with
- `Provider` - One of the additional properties being introduced in the issue above, described as "Displays the source or provider name (e.g., CaDeT, Justice Data, NOMIS)." It could be that we're getting a bit tied in knots about how to populate this field, we convinced ourselves that this is better set to AP as that's more what users care about but maybe that's not how this should actually be used.

Could we better use Platform to cover the above areas? 

We can define [custom data platforms within datahub](https://datahubproject.io/docs/how/add-custom-data-platform/)

The majority of datasets are currently assigned to the default platform as per their ingestion source so:
- create-a-derived-table: `dbt`
- source data available in the APa via aws Atehna: `Glue`

But do these have much meaning to users of find-moj-data? It might be better if we override the platform with `Analytical Platform` for both of the above and use datahub's platform in general to be more indicative of where the data are hosted an availble to use/consume from an end user's perspective.

### Questions to answer
If we adopt the above could we make better use of the Platform to display useful metadata to users in find-moj-data? 
Is it possible to assign ingestions from different sources to a common custom platform in datahub?

## Custom defined Platforms
We do currently create some platforms but these are made as a part of ingestions (eg. [justice-data](https://github.com/ministryofjustice/data-catalogue/blob/main/ingestion/justice_data_source/source.py#L70) rather than being defined in code independently as [custom platforms](https://datahubproject.io/docs/how/add-custom-data-platform/)

The platforms created this way are:
- `justice-data`
- `esda`

We should define these platforms in code (maybe this can be separate issue)

**Comment by murdo-moj** [comment]
I think we should keep them all

The idea with `dc_where_to_access_data` was that it would be higher granularity than Provider and link to a specific project file in database access (for instance) where you could get access to that table/dataset. Which is still a valid use case, it's just unpopulated.

The difference between platform and provider to me is small, but Provider is understandable to the user where platform is more useful on the backend where it matters to us if an entity is coming from glue or dbt. For example if we have a problem with an entity and need to trace it's ingestion, if all AP entities have the platform AP then it's less clear where the ingestion comes from.

**Comment by MatMoore** [comment]
notes from huddle this morning

Option 1: create new platform/platform instances
- AnalyticalPlatform
  - CaDeT
  - Glue
- Justice Data
- GOV.UK

Option 2: keep provider field and get rid of dc_where_to_access (get rid of it from CaDeT as well, remove mentions in user guide)

**Comment by LavMatt** [comment]
## Option 1 - Overriding Datahub's ingestion source default platform

This option was to explore whether we could create custom platforms and direct datahub source ingestions into these platforms rather than the platforms they default to because of the source. e.g. dbt is loaded into the dbt platform, Glue is loading into the Glue platform.

On looking into this more closely **it is not possible to override the platform for the source ingestion**, e.g. `dbt` or `Glue`.

If you use the dbt ingestion source, the ingestion recipe cannot be configured to load the data into a platform other than dbt. 

What is possible to configure is to load the data into a custom target platform. We currently load the data into Athena as the target platform.

This is not helpful for the way we are using the target platform entities in find-moj-data though as these Athena entities are siblings to the dbt ones and do not hold the same level of useful metatdata (column names, descriptions), and we already ignore them in the front end (else they would present like duplicates).

See dbt & target platform set as Analytical platform
![Image](https://github.com/user-attachments/assets/7ffcf3bc-bc89-4314-8d57-e6e277870af3)

See any useful schema metadata is missing for the target platform entity (Analytical platform)
![Image](https://github.com/user-attachments/assets/f319e22c-b15b-4572-a598-ee4b4e3999df)

Target platform is created as a sibling entity for dbt ingestions however there is no option for a target platform entity in glue ingestions. So we could potenitally use the sibling entity platform for dbt ingestions but this is messy and overcomplicated and not extendible to other sources Glue (and likely others we could use in the future)

**This is a major blocker for Option 1 and means it would not be possible**

**Comment by LavMatt** [comment]
## Option 2 
### Use a common custom property to collect the hosting platform metadata for ingested entities

**Comment by LavMatt** [comment]
## Option 3
### Map a combination of properties in datahub to platforms as we'd want to display in Find MoJ data

This would work by returning both the platform and platform instance of any entity in our graphql queries and through the combination of these properties map to a platform as we'd like to display in Find MoJ data.

We would need to change the platform instance we currently use to implement this option as we'll soon have cadet data ingested that are hosted on platforms other than the analytical platform.

As an example of the mapping could work like:

![Image](https://github.com/user-attachments/assets/5c633623-e603-49ff-a16a-8d48dc87213b)

**Comment by LavMatt** [comment]
We'll look to implement option 3 and test with users about how best to display this metadata
