### ISSUE TITLE
Spike: metadata completeness

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/data-catalogue#39]
Following on from ministryofjustice/data-catalogue#62 

Create a report/dashboard which pulls from postgres (DataHub entity store) to display metadata completeness

Could be:
* Superset dashboard
* A page on find-moj-data which live queries postgres
* A scheduled workflow on find-moj-data which feeds a static file for a page, to avoid loading the database so much

**Comment by murdo-moj** [comment]
#62

**Comment by DeanWillicombe82** [comment]
Needs More clarity around whether this if for Non-DIP users or DIP related.
