### ISSUE TITLE
🚨 Screenshot before and after UI changes on datahub and find moj data pre💥

### ISSUE THREAD

**Issue by YvanMOJdigital** [ministryofjustice/data-catalogue#9]
For alpha assessment pack please capture all before and after UI changes in a screenshot before merging to environment. This helps us show our iterations and responses to feedback. 

Please post them in here for reference.

**Comment by MatMoore** [comment]
## Before

### Search page
![Image](https://github.com/ministryofjustice/data-catalogue/assets/87579/60aed00c-af94-4fd2-9eac-d2ea762fdda1)

### Data product detals

### Dataset details

### Glossary

**Comment by MatMoore** [comment]
## Datahub data product views before


![Image](https://github.com/ministryofjustice/data-catalogue/assets/87579/a4954459-6cd8-4c01-ae48-f3ae94377639)



![Image](https://github.com/ministryofjustice/data-catalogue/assets/87579/51e3934b-3eb0-48d1-b2c7-30985ec6828a)

**Comment by MatMoore** [comment]
Filters during second round of user research



![Image](https://github.com/ministryofjustice/data-catalogue/assets/87579/b4f7b144-30ec-43e3-bb32-730aafe5421a)
